name: Build Typescript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Start build
        run: npm run build

      - name: Upload release asset
        uses: actions/upload-release-asset@v2.6.1
        with:
          upload_url: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist
          asset_name: Scripts
          body: "Scripts release for Discord Bot Builder"